tweets = [
    'Y solo ten mi numero telefonico',
    'En días como hoy, me estoy preguntando si seré la única que no juega Pokémon GO\U0001f914\U0001f914',
    'Ahora si se arma el mierdero 😂😂😂😂😂😂 https://t.co/OFleoLfd0b',
    '@angelgcc vi el video una lastima... he visto las olimpiadas por RCN y la entrevista muy bien hasta conexion con la familia en Colombia',
    '⒈ #HoyJuroQue\n⒉ #NoMeVuelvoAEnamorar\n⒊ #SaltoConGarrocha\n⒋ #RetoYoPuedoSolito\n⒌ #NoQuiebrenArtesEnLaNacho\n\n2016/8/16 01:07 COT',
    '⒍ Shaunae Miller\n⒎ Torres\n⒏ Francés\n⒐ El 15\n⒑ Atlético Huila\n\n2016/8/16 01:07 COT #trndnl https://t.co/cSmLh2Ssg4',
    "le iba a decir al coño que lo iba a compañar hasta cabimas pa' escuchar vallenatos",
    'Hay que elegir sabiamente o locura será tu nombre',
    'Es 16 de agosto😭😭😭💔💔💔💔.',
    ':(',
    'No hay mejor vividero que sincelejo creanme he conocido lo suficiente para estar segura de eso!!!',
    '@jambrak Jejeje Vaya Yo Pensando En Ti 😂😂😂😂 Me Has Hecho La Madrugada',
    'Ya me vi durmiendo ahorita en clase😥',
    '@isaacpdro99 @JosephNieveeees  AJAJJAJAJA busquemos oficio vee JAJAJ todos dos son unas papis ricos jajaj',
    'Dios no esta muerto 2, es una bellísima película! 😍',
    'Y me diste el hombre, yo soy tu niña, la niña de tus ojos, porque me amaste a mi🎶😍😍😍',
    'El peor día del año💔💔😭😭😭.',
    'Ay no :( x2',
    'College is fucking cake idk why people trip just do your shit on time lol',
    'Nuevos productos para una deliciosa tarde de te ... https://t.co/yngoTZBS6W',
    'Lo que es para uno es para uno.',
    'Y yo como tonta recordado la fecha... 😔 que inepta !',
    'Cómo se recompone lo intangible?',
    'Porque tendré la piel tan delicada😞😞😞',
    'Medalha pro Danton... #BaladaOlimpica https://t.co/q4N7MfE06z',
    'Pues sé que ese beso es para mi, la razón de mi vida.',
    'Dios, cuida a las personas que no tienen un techo con este aguacero tan tenaz...',
    'Mañana tengo ocupado mi día desde las 8 de la mañana jajajJaja que gonorrea 😍🙈',
    'Ella es la sensacion del bloque',
    'WhatsApp #macabeojoyas 3106808424 – 3103310343 #fashion #style #stylish #love #TagsForLikes #me… https://t.co/P4S0lN2CtL',
    '@MaryLauGomez PENDEJITA 😂 jajajajaja',
    'Que bonita esa estrella 😻',
    '#ElPlanetaalRevés cuando las fugas de agua son del operador como en Buenaventura y se hacen los locos @Superservicios @Minvivienda',
    'Curso mencionar???? Jajsjajaajaj https://t.co/oWxVOUXpfx',
    'Te das cuenta 😏',
    'Yo muevo mucho la cama de lugar, casi siempre que limpio la habitación (una vez al siglo), y siempre la pongo cerca de los toma-corriente.',
    '@GerznMg otro fracaso de la lucha nalcanzable de DC Comics a Marvel https://t.co/9EQknswe9e',
    'Carajo, se va a caer el cielo aquí ps! 😂😂',
    'Locura de trastornos, arrepentimientos y muchas cosas más..',
    'Hpta inestabilidad emocional la suya!!!',
    'Cuentale que te conoci bailando cuentalee',
    '@ElEmirr_ a la vrgaaa... Puedo******',
    'Hoy y estaa cumpliendo una parte de mi 💕',
    'Mi sueño es ganar un premioooo',
    'For ever 💕👫🌈😇⛅ https://t.co/fo3Ig1EXts',
    'ah vei a elke maravilha morreu memo',
    'Tercer Cielo - Yo te extrañare😭😭😭😭😭💔 &lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;.',
    '@angelgcc emociona ver la entrevista en el caso colombiano....',
    '- "Una erección de 99millones de años"\n- Yo, desde que estoy soltero 😀😁😁 https://t.co/GmmeUdDq0M',
    '@COOMOTORC mucho desorden, pésima atención y servicio https://t.co/vV3chyiUz5',
    'Fav si arrobo al último que me dió besitos',
    'Hay nuestro amor se acabo.',
    '... https://t.co/5D0yJnrDz8',
    'Mañana va a ser un día laaaaaaargo',
    'Quiero terminar de ver la película no me quiero quedar dormida no😭 #SebastiánVillalobosVideo #SebastiánVillalobosYoutuber #KCAColombia',
    'Como dice mi hermanito, borrador con eso Mile',
    'La negación es el primer paso 😂😂😂',
    'Mi nombre por aquí...\U0001f595 https://t.co/MnLaVpmpXc',
    'Dicen que el amor es un mal necesario....',
    'Cometassssssssss💫🌠 https://t.co/2bBxILvFYY',
    'A ella le gusta la gasolina',
    'ya va yo iba hacer algo y se me olvido a raro',
    '@telenovelo @superfan33 @AzelaRobinsonFc @azelarobinson no se como si no tiene nada de buena es aburrida',
    'AJAJAHAJAJAJ https://t.co/M7zXLMDUoh',
    'Ojalá pudiera devolver el tiempo para verte de nuevo, para darte un abrazo y nunca soltarte.',
    'Ilym gorgeous ❤️❤️ https://t.co/Jea8MseKJ8',
    '@pielpret2 beautyful an hungri',
    'a lo bien con los muchacho\ndel buen peloteo ⚽️⚽️⚽️⚽️\n🏆\U0001f3c5 https://t.co/CUTYJ4Mo0j',
    '"Cuando uno ama a alguien ama a alguien a pesar de todo"  camp',
    'Y yo por el capítulo 7 de esa👇 https://t.co/Hj8T0HFfCv',
    '@oliveirapaolaa_ kkkk',
    '@ToyiSalleg @StiphanyMA para por favor, ya es hora de dormir, no más corta venas, y partida de pistones.',
    'No te compares con nadie, ten la cabeza bien alta y recuerda: No eres ni mejor ni peor, simplemente eres tú y eso nadie lo puede superar.',
    '@GabrielaR___ ps @migato kien +',
    'Quizás sólo necesite un tiempo.',
    'La grandeza con que @casciari narra la vida que todos vemos, hace más que ponernos a pensar, estimula la imaginación y relaja la existencia.',
    'No sonrías más porque me enamoro, y enamorado soy severo encarte.',
    '@carfe2004 jajajajaja lo sé fer',
    'Me voy a arrunchar a lo mío, bai.',
    'Gata fieraa, ami no me vas aruñar',
    '"En sus ojos apagados hay un eterno castigo; el héroe de leyenda pertenece al sueño de un destino".',
    'temperature down 17°C -&gt; 15°C\nhumidity up 97% -&gt; 100%',
    'No sé qué problema tiene mi cel que desde que lo tengo no deja de vibrar hasta que lea o borre las notificaciones de todo.',
    'Es que yo te quiero , es que yo te adoro 🎶❤️ https://t.co/ByfSZDvoJv',
    'Im not so whats going to happen? 😄 https://t.co/1qlULVOeQD',
    'La va a leer el coño e tu madre, ando sin lentes :c https://t.co/2VTwhGip5X',
    'Jajajaaaaaaaaaa qle poco😂 https://t.co/MnLaVpmpXc',
    'Nada que aprenden a dormir temprano, que cosita con ustedes.',
    'Odio toparme con fotos de Janis Joplin. Me desagrada demasiado',
    'Soy taaaaaan llorona #SebastiánVillalobosVideo #SebastiánVillalobosYoutuber #KCAColombia',
    'Aún duele muchísimo. https://t.co/WaUArCFI2O',
    'La come trapo y a dormir',
    '"Un sueño sólo muere cuando se ha hecho realidad"',
    'Vou ir fazer xixi e dormi porque infelizmente só tenho cara de patricinha mesmo,hahaha Trabalho daqui a pouco.. Boa noite #Fui',
    '@MaryLauGomez JAJAJA tú sabes que no hace falta decirte Pa que sepas quién es 😌',
    '@Agunnermore ash, quería que supieran',
    'clear sky -&gt; few clouds\ntemperature down 17°C -&gt; 15°C\nhumidity up 82% -&gt; 93%',
    'soy una mala madre que le envía gifs de muñecos diabólicos a sus hijos cuando tienen miedo',
    'https://t.co/ml6yljS8pE',
    'Visualmente',
    'Yo forever https://t.co/2tHPsvQWj1',
    'Pablo Alborán - Desencuentro (Directo) - Tres noc…: https://t.co/tsnZSn3b4H OOOK la melodía.',
    'oye don luchar por amor',
    'Wake up, you need to make money',
    'Y me gustas por que eres diferente.',
    '@enriquepvasqz soy tú',
    'Después dice que no es gobernada.',
    'Cara, como q faz pra dormir cedo?',
    'No quiero dejarte ir, pero es absurdo aferrarme a algo que finalmente NO quiere quedarse y tampoco me pertenece...',
    'Si yo soy virgen de labios ._.',
    'Bien sabes que te ameeeeeeee SIN LÍMITES!!!!',
    'Yo no soy tu marido ni tampoco tu hombreeeee',
    'Menores 👽 #Panamá #RepDominicana &amp; 🇻🇪 https://t.co/KrAvynskvE',
    '@jimenaofficial Para que nos casemos?',
    'Lo sabía, puede doler tanto...',
    'Me voy y a los días clase, back to reality 😰',
    'Racata racataa',
    'Hola',
    'WhatsApp #macabeojoyas 3106808424 – 3103310343 #girly #pink #girl #girls #eyes #model #dress… https://t.co/vdBANxBDcl',
    'Ella destruyo mi alma una vez mas',
    'Yo creo que al final a las ex parejas se les debe más cosas buenas que malas, así que no odien sus elecciones, algo bueno habrán dejado.',
    'Si c fue c fue',
    'SÓ QUERO SÁBADO!!!! SÓ VEM PEACEEEEEEEEEEEE',
    'Dame otra oportunidad, y juro querrás envejecer conmigo',
    'Esta hora no esta pa lo cursi...',
    'https://t.co/mXlfrqiCL3',
    'Usted tranquila que ese primer pensamiento diario no se lo va a quitar nadie, ah ni el último de cada dia.',
    'creo que me voy a dormir (dormir para mi se define como escuchar música hasta no dar más)',
    'Yo quiero ver como tu cuerpo me provocaa',
    'Como pasan los dias',
    'Que hago me mato ?',
    '@YouTube where are you????,,buenas noches mundo\U0001f596🌌',
    'Un "no me pasa nada" es un "me pasa de todo"',
    'O pico mais louco, o jeito mais sujo, irmão!',
    'Un senador paquistaní amenaza con violar a una activista en televisión https://t.co/RicA6TFfkS vía @PlayGrounder',
    'Por dios 👏\U0001f3fc👏\U0001f3fc https://t.co/QYVPzGiLGj',
    'Joda no mk-.-',
    'Uy estoy drogadísimo',
    'Hoy seguro me quedo dormida en la clase de Sociales, como vamos a ver película pues aja 😂 #SebastianVillalobosYoutuber #KCAColombia',
    'Yo no sirvo para eso.',
    'todavía haciendo tareas :( jajajajaa',
    'Otra? https://t.co/Hp6VeoLfR4',
    '🌺 https://t.co/VSJWgctisA',
    '@StalkeameEstas Jajajaja se hizo el 🍑 y las 🍒 con un cirujano que tengo en Holanda 😁',
    'me beffa me hace reír re harto',
    'Cuanto SPAM! ☹️😂❤️ https://t.co/HtrS6AjN0q',
    'Tu sabes que somos de calle siente el fuego las reglas del juego las pongo yo',
    'Me estoy preguntando últimamente si seré la única que no juega Pokémon GO\U0001f914',
    'Ke no vuelva +',
    'Epaaaaa ajjajajajajajakajakaka',
    'Tengo clases dos días después que me voy 😰',
    'Time to sleep! Buenas noches a todas y todos. Menos para quienes duermen con ropa, a ustedes no.',
    '@connorfranta @liampayne @troyesivan goodnight lovelies 💕💕',
    '@Carmen_spetit jajsjajsjajsa',
    '@MaryLauGomez Jajajaja esto me mato 🙌\U0001f3fd Jajajajja la bruja Gómez 😂',
    'Dímelo my nigga! 💀 https://t.co/84DchdbCHN',
    'Fav ❤️ https://t.co/6YBbyemhsB',
    'Incluso si no estamos destinados, te amaré como si fueras mi destino',
    'Hace mil años que no abría esto😂😂',
    'Que bella estas luna lunera💕😻',
    'amo a connor liam troye y caro bye',
    'True that..! 💭 frases que escuchas y tienes q escribirlas 📄\U0001f58b para empeorar tu insomnio 😂 #epicfail https://t.co/1IJzgZL0dI',
    'Aparentemente no, no te quieren conmigo',
    'Mi mamá y mi hermanito escuchan reggaeton todo el día, OK.',
    '&lt;------ es muy hembra para llorar por un huevón',
    'descansen xx https://t.co/RqdNc5CWDj',
    'eu to um caco',
    '@jambrak Jejeje Minimo 😂',
    'Esta pensadera no me deja dormir 😞',
    'Jajajaja el tarri por aquí por el barrio baia baia.',
    'Tout sera différent cette fois ma vie😻🙏.',
    'Le preguntó al espectador cual es el miedo ah. Creo que algunos colombianos no tenemos miedo pedazo de hijueputa hijo de ramera.',
    'A veces me aburree',
    'Jajajajajsjjsakajsjs ganarrea, ke estoy escuchando',
    'Cada quien vive su fantasía',
    '@isaacpdro99 @JosephNieveeees  JAJJAJAJA sii sii isac sii ya calmate  ya lo sabemos jaja',
    'Somos hojas en blanco buscando colores en personas obscuras',
    'Hoy es noche de sexo, y voy a devorarte nena linda',
    'e ainda ficam de palhaçada',
    'Hay personas que aunque yo salude (por educacion) JAMAS seran mis amigos! O si quiera considerados "conocidos"...',
    'Desperdiciamos el tiempo en cosas inútiles. https://t.co/CDujdgEPgX',
    'Te extrañare linda capital💗',
    'Que estrés que a toda hora lo tomen a uno como un jueguito, tan maricas.',
    'vai se fude',
    '😴',
    'https://t.co/of826lPmuV',
    'Saca tu memoria de esa prision',
    'En serio mi reacción para todo lately y por siempre https://t.co/0MG7LtYhj2',
    'Esto es para ustedes pa que se lo gosen',
    'Por cierto, te iba a preguntar, qué hace Larry dURMIENDO EN MI CAMA.',
    "heaven it's a place on earth with you @mangelrogel",
    'Assumptions',
    'Intento dejar de usar mis redes sociales para ver tv como alguien normal sin usar Internet pero todo lo que dan es repetidisimo y aburrido 😐',
    '@daviidparra3 hola',
    'quitate tu pa ponerme yo vamo a vel aqui quiene s quien',
    '@Vipertooth_ALE @LiizBetty ýo se q me odiaras por esto pero yo te lofiu amiga :* q conste q esa es la mas formal jaj https://t.co/WGpLs98Bu0',
    '2:18am no tengo nada bueno que hacer con mi vida',
    'Pero tu no te preocupes girla, siempre soy ganador y así es que se celebra!',
    'i hate u, i love u, i hate that i want you, you want her, you need her, and i will never be her...',
    '@isaacpdro99 @JosephNieveeees  JAJAJJA bueno se me calman aqui no van a botar las plumas ajja',
    'Se que hay bonitos recuerdos pero no es de cuerdos tener recuerdos por obsesion',
    'AWWWWWW YA PICHU ME DIIIJOOOOO😍😍😍',
    '#BaladaOlimpica https://t.co/hLGCK0cFSc',
    'Que se sentirá? ?? https://t.co/B4P7i5IOiT',
    'somo asi undergraud estamos aqui bien potiao',
    'Jajaja esto sí lo leo y no lo creo, me quité.',
    'Si pudiera describir solo con palabras como me siento. Decepcionada, Avergonzada, Dolida, Lastimada, Furiosa.',
    '@Anita__Carrizo esta bueno jaja',
    'Les duele, mi felicidad. https://t.co/N5eRg3X5Rl',
    'Todo está dicho... https://t.co/S1sYkYbtia',
    "@abc_d_n Oh how I miss you... I miss you and I wish you'd stay",
    'Empaca tus sentimientos y llevalos en un bolsito hasta que el tiempo te diga donde se sacan',
    'Que beelloo',
    '@lauramarrrr blonde vs brunette https://t.co/50yFgHCgnC',
    'Dicennnn',
    'La vida es loca y eso es lo que me toca.',
    'Según Banco de la República la inflación comenzará a bajar en agosto https://t.co/UJpY28ELq7 https://t.co/Gl4u9gAU7m',
    'Gracias a @schneider_9408 no consumo nada.',
    'Desde que entré a la u este año no he dejado de dormirme antes de las 3 am',
    'Porque negra tengo el alma...  Esa es la mía https://t.co/pFPrFmf58c',
    'Estoy tan aburrido no se si llorar,molestarme,sentarme a pensar buscarte o simplemente esperar...sigo dudando que de algo sirva rezar...',
    'De novo... https://t.co/hxqTTWzSH2',
    'EL EXTECNICO DE INDEPENDIENTE DEL VALLE TAMBIEN ESTUVO EN UNA PELICULA PARA ÑIÑOS #elegant https://t.co/dQkFoLXu7q',
    'Chaoamr, madrugo a las nueve.',
    'yo soy una buena persona :(',
    'Usé pañal hasta los 9 años y para ir a la casa de mis amigos a dormir tenía que pedirle a sus Mamás para que me lo pusieran 😳',
    '@iMarialaura tienes barba o son las drogas',
    'El helado, la fresa y la crema se quedan conmigo.',
    'no puedo dormir',
    '@schneider_9408 Sólo diré que la próxima no se demoré tanto para darme un abrazo.',
    'No me gusta los horóscopos stoppp',
    'enhorabuena por los albos #67AñosHaciendoHistoria @CremasOficial mi equipo de guatemala el mejor',
    'Policía de Córdoba capturó a presunto Jíbaro https://t.co/F8I6cUSblC https://t.co/OLOuAfLnjg',
    'harley quinn',
    'Que situación más paila😪',
    'Sigan @MueblesNunezM &lt;3',
    'lo que aquí pase va quedar solo entre usted y yo.',
    'Sin internes no fifa.',
    'Nacer, crecer reproducirse y morir',
    '😍😍😍😍 https://t.co/6RGUws5DUn',
    'Tanto Daño Que Me Causastes💔 https://t.co/nQ2lUufqhc',
    '@NicoleMParedes my dilemma rn',
    '@LuisValenciah2O @WinSportsTV Cagadero roliviano',
    '@justinbieber  asi nos hiciste sentir 💔💔💔 https://t.co/qfILiWWK52',
    'También me pasa https://t.co/MmhdlRWTLR',
    'Me volvió el alma al cuerpo, blufff💘',
    '#instafat #tropaR increíblemente lo que mas miedo y temor me da, lo que en por nada del mundo… https://t.co/7zfkTySLu0',
    'Ma#ana voy a tener la casa sola.. eso significa ??',
    'La justicia, p/ el NarcoRegimen,\nno es + q 1mercancía pública y\nel q preside el tribunal\nratifica las transacciones. https://t.co/7eoi2rMrAP',
    '@liliavt99 bah tu n esqueceu disso tieee kkkkkk , só no verão kkkkkkkkkkkkkkkkkk',
    'Tu eres muy malo fren... https://t.co/R6RQENw5FU',
    'Por la plata baila el moño y aquí yo soy KING KONG.',
    'Jejeje Sera Que No Tiene Nada Que hacer 😏😂😂😂',
    '@narethserna ¿qué le pasa a tu mami? Fuerza y bendiciones, hermanita',
    'You: https://t.co/5RBpEGMuBB',
    'El hashtag #SoyMedallaDeOroEn ocupó el lunes 15, la 6ª posición en el Top20 de las Tendencias de Colombia: https://t.co/3YpmjkyML5 #trndnl',
    'ok entonces estaba totalmente dispuesta a dormir. Fui al baño como de costumbre antes de dormir y me encuentro con una secta de cucarachas',
    'Mi piel extraña tu cuerpo !!',
    '@thaysalejandraa Jajaja sí!',
    'FALTO PUMA https://t.co/NsyGJTANkW',
    'Difícil entender LAS RAZONES DEL AMOR.',
    'Estar vivo no es precisamente igual a   vivir',
    "i'm in love with someone else's girl, you rock my world, but you are the one that i cant have",
    'Pacifica o pacense, no se pero amo mi pueblo !!!',
    'quería sacrificar a una virgen (yo era la virgen)',
    'lmao esta foto https://t.co/3t11ltM12b',
    '@isaacpdro99 @JosephNieveeees  uyy como enserio jaajjaa no creo sera ??',
    'Me Quiero Pintar las uñas de negro 😏💅',
    'Estoy enloqueciendo!',
    'Mañana voy a ir a jugar billar con romero y si  necesitaba de un plan como esos. 😍😍😍',
    'Son vainas mías o el internet está lento?',
    'A ti te odie como 3 dias... https://t.co/NMFgtAYrGv',
    'I need you all the time.💔',
    'Bésame despacio y no se te ocurra dejar libre ningún beso ni ningún espacio',
    '@dorianigdma Soy fotógrafo busco chicas buena presencia como tú, para un proyecto, sígueme y te explico, saludos.',
    'Larga vida a las personas con gran madurez.',
    'JAJAJA no pensé reírme tanto😹😹😹',
    'Si ir a cine es salir con alguien!! No me imagino que será cuando uno se acuesta con esa persona... Ahí qué me caso?',
    'querían vale, querían*',
    'Oyé tu sigue mi paso bebé. https://t.co/JlSeHh1cQR',
    'Quero fritar demais na Peace sábado se loco',
    'quien tiene cotufas?',
    'Mi jeanca💕 https://t.co/1VYvFCZoKP',
    '"Deja q te bese, deja q lo intente ..!',
    'Hay tanto que quisiera no haber descubierto!',
    'Alguém me indica um filme bobinho pra assistir antes de dormir, porfavô!Apenas estou com dor de estomago depois dos dois últimos que assisti',
    'JCG',
    '@liliavt99 to vendo eu tbm kkkk , o cpx vou dormir eu q amanha a correria é cedo ... haha',
    'hambre 24/7',
    '@MeryChV esto es lo único que me queda por hacer estoy dormidísima, se me apagó el celular y vos no llegás, ¿qué puedo hacer yo?',
    'Admito rotundamente a @Guautaa por haber hecho todos los 82839372919 trabajos que teníamos D:',
    'Gente con más de 20 años y no saben qué hacer con su vida, yo con 16 tengo planes de vida y todo.',
    'I moved to Panama to avoid student loans. My dad offered to pay for my school if i majored in law here &amp; i dont completely hate it',
    'Con razón tanto odio 😂😂.',
    'Ya hoy se muda mi bebé, ay noooo😖😖😖😖😖',
    'Sleeeeeep',
    'Tengo la sed mas hijueputa de la vida *c compra una pola*',
    'Yo a veces me complico por nada',
    'mis originales https://t.co/R9cyplUym1',
    'Jeje! https://t.co/Hq7ZUwYU28',
    'Yo no sabía que con un beso se podía parar el tiempo y lo aprendí de ti',
    '#goodnight me #selfie #moments #cutegirl 😘😘 https://t.co/Sx1g4tyzBE',
    'Mongolo',
    'O que eu tenho em casa faz eu não querer sai',
    'Mi mente es mi peor enemiga!',
    'del susto se me quitó el sueño esto no es de dios',
    '@schneider_9408 *Recordando colineras del 20 de Julio*',
    '@migueeecarrillo po quéee',
    'Ok, disculpe usted buen señor... https://t.co/KF4D4RR5d7',
    '@nathyochoa Ando por caminos mas sanos que los tuyos!',
    'O que eu tenho em casa faz eu não querer sair',
    'De esas cosas que suelen pasar.',
    '\U0001f644✨ https://t.co/8S2wGv0FUo',
    'Y ahora si, buenas noches para todos❤🙌\U0001f3fb',
    'Me dijo, te dire lo que es mentira sin pensar el daño que me haria..',
    '@liliavt99 ai sim tu q ta falando kkkkkkkkk , pdcc flw....',
    'Admiro*',
    'Ya se me está haciendo costumbre desvelarme sin ningún motivo. 😭',
    'todo no es para siempre q pensaste q te amaria toda la vida iluso😆 https://t.co/NLhOi0Xr8B',
    '@MirachAndromeda qué ocurre',
    'Va a caer rolo palo de agua oyó.',
    'Ya a esta edad es pa saber qué coño quieres ser y qué coño hacer con tu vida',
    'Horsea es el que debería haberse convertido en Gyarados, y no  Magikarp, hahah',
    '@CarlosCob0 Buen día, Carlos por favor ayúdame indicándome tu novedad y el numero donde mantienes el inconveniente por DM para ayudarte.ER',
    '@rcdf_ pero pero :( jajajajajaja',
    'Como cuando quieres llorar mucho y decir tantas cosa que tienes adentro y sacarlas 😔😞',
    'Como no te voy a amar si siempre te lo demuestro💕',
    '¿Y la Felicidad que?',
    'Putos gatos, cuando tienen hambre no te dejan caminar.',
    '@gaymasweb beautyful mens',
    'La chama es linda',
    'Huele a lluviaaa🍃',
    'Parce tengo tanto frío que estoy tiritando.',
    'Eras mas taquillero que el titanic... https://t.co/CcxjJqAweW',
    'No tengan novias que se desmaquillan mientras intentan dormir por favor !!! #MuerteAEsas',
    'Tengo varias noches pensando en ti',
    'Trabajar duro. https://t.co/gtMwlVyO4n',
    'https://t.co/PG82xM5cuK',
    'Oren por mí.',
    'Deja de darle "me gusta" a mis cosas, maldita gafa.',
    'en serio no es de dios ya no tengo a nadie con quién hablar ahora qué hago sin sueño',
    '@lmjreason aconteceu isso comigo mes passado, liguei no support da apple e a moça disse que a unica maneira é restaurando pelo iTunes',
    'Tirarme hasta el casco por una borrachera neeee qué visaje 😒',
    '@iMarialaura dejaré guardado tu avatar y cuando se me pase confirmaré maria barbara https://t.co/QZlCWaDY79',
    '@abc_d_n @SantaFe Jajajajaja:( vamo a llorar #Quebuenahinchaperolacopaesaveznosequedoconelleon:(',
    'Horsea es el que debería haberse convertido en Gyarados y no  Magikarp, hahah',
    '@EddyBleik tu solo trasnochas..',
    '@WyznickOrtega aja',
    'https://t.co/F8VcHx0WBB',
    '@MirachAndromeda me veo mocho',
    'No voy a dormir nada ya😩😭',
    'Uno madura con los golpes.',
    'agr é aguentar no osso do peito como sempre',
    '@Rusbelyromero_ @chinamedicen_ vergacion y dígame yo no casi q no las extraño las amooooooo',
    'Como tu no hay.',
    'https://t.co/UWth0lFL7I ag lo mío hace cosas re chimbas',
    'No meu coração fiz um lar... O meu coração é o teu lar e de que me adianta tanta mobília, se você não está comigo?',
    'Gracias por enseñarme lo que debo mejorar, y saber que no a todo el mundo se debe pedir Perdon!',
    '-TEO CUIDADO AHI VIENEN LOS HINCHAS DE MIYOZ\n- https://t.co/PeOvEp9IKJ',
    'y ya me vi todos los videos de phineas y ferb ayer que chimbo',
    'tengo ganas de salir pero a la vez no',
    '@Danizoavila literal jajajaja',
    'Desde hace 10 años me haces la tia mas feliz mi princesa andre 👭👏🎉🎈👧 Dios te protega siempre mi nene linda te amo💜🎂 https://t.co/AzfUmufIlL',
    'El mundo da mas vueltas!',
    'te voy a querer te voy a adorar lo juro por dios, porq tu eres mi sool',
    'Como dice mi mamá menos mal no me pasó nada 😇😥😥',
    'mucho mucho',
    'vou dormir , pdccc ...',
    '@EAristeguieta En legítima defensa y dentro de la constitución. Nada está excluido. https://t.co/iuB5UOOv9z',
    'Tu Eres Mi Vida Ahora😍💖',
    'Me va a tocar hablarle a mi. 😂😂',
    'Jajajaja 😂😂😂 https://t.co/P5dU7JwoAM',
    'Nos fuimos lejos..',
    '@migueeecarrillo nunca',
    'Só é possível te amar.... Escorre aos litros... O amor',
    '@mylojose Gracias, eso haré :)',
    'Que quiero y no puedo querer mientras siga queriendo..',
    'Alguien por ahí',
    'Como he vivido mi vida',
    'Porque é difícil dizer tchau quando a noite foi na moral',
    'Que frío tan hpta',
    'https://t.co/zqDsSJcz7y',
    '"A esta hora salen las palabras más sinceras, duérmete antes que se las digas a la persona incorrecta".',
    'Alguien por ahí?',
    '@MiIlonariosFC cómo twittear éso? Pechos fríos, han tenido ha más de miles de nosotros en un peor momento que ha durado más de 28 años.',
    'Esas con delirios de prepago, jaja nada que ver😂',
    'Mi lámpara se terminó de joder.',
    'Liricazo',
    '"Con Dios todo es posible"',
    '@Frankyardigan JAMÁS. Yo soy más de Alaska.',
    'Siempre mi viejito👫🌠. https://t.co/MAHVqM90md',
    'Personas como estas necesito en mi vida perros UNA VEZ MAS TE GANAS MI CORA MOMOCHAAAA😍🙈🙈🙈🙈 https://t.co/awp02weafg',
    'BIEN LOCO PARA PODER DORMIR.',
    '@abc_d_n @SantaFe Jajajajajajaja:( #Lacopaesaveznosequedoconeleon',
    'Me gustan los flacos!😳',
    'Trate bien a varias PUTAS, y trate mal a quienes me Querian ...',
    'Cuando solo estemos tu y yo',
    'Tu y yo viajando a marte😳💭🌙🚀',
    '...😔☹️ https://t.co/eaPOmzCkb2',
    'Bogotá manito, cual Aguacero 😣💔',
    'Familia que habla a tus espaldas, no es familia, ahí les dejo.',
    '@dubidubachu y había que entregar las malditas laminas',
    'A esta hora solo publican vídeos de tatuajes y qué ganas',
    '@fuckingacid_ Soy fotógrafo busco chicas buena presencia como tú, para un proyecto, sígueme y te explico, saludos.',
    'That day we thought we were harder than nails because we kicked around on… https://t.co/I6CN82Iwos',
    'Que rabia tan grande cuando un tweet está mal escrito.',
    'A veces bien, a veces mal..',
    'Jorge Lusi? La Para? Jorge Luis? SI MI AMOR NO MI AMOR NO MI AMOR jajaajajaajajajajajajajajajjajaajajajajajaajajajaajajajjaajjaja😂😂😂',
    'Perdonó cosas peores se la jugó por alguien. Que jugaba con ella y soy yo el más malo de la historia... Pero por favor!',
    'Digo la verdad hasta cuando miento!!',
    'Mi avatar esta muy serio de pana me gusta',
    'Ser humilde no cuestaaa... \nSolo que algunos(as) personas no conocen… https://t.co/W5MMJweQXl',
    '"Mas que un hermano haz sido un brother" JAJAJA\n#SebastiánVillalobosVideo #SebastiánVillalobosYoutuber #KCAColombia https://t.co/dyEMNjvqXx',
    'Ya no saben qué más decir, yo soy el que siempre estaba ahí...',
    'No puedo no que fastidio justo en este momento',
    'Y después soy yo... Mmm https://t.co/Xz24yr7enc',
    '@schneider_9408 Ya no jajajqjq',
    "Alrededor de 45 jóvenes participaron en la ''Clínica Skate'' en #PuertoCabello (16 - 8) https://t.co/MtZJChiZUT https://t.co/dWlIIDOSx7",
    '@WyznickOrtega mana es una copia de suelta la sopa que arropa a todos los paises de centroamerica y america tvn lo permite y quien de wichi',
    'No hay sensación que se comparé con escuchar las gotas de lluvia golpear mi ventana a esta hora.',
    'Le gusta es su mala vida.',
    'ESPERO VENEZUELA HAYA VISTO LA ENTREVISTA DE VLADIMIR VILLEGAS ESTE LUNES CON 2 GRANDES ECONOMISTAS LO QUE VIENE SON NUBES NEGRAS',
    'Pasado pisado, a lo hecho pecho!',
    'La hora que es y no hemos logrado llegar al peaje de chuzaca @TransitoPolicia desde Fusagasugá. Varados en la vía por trancón recalentados.',
    'Cuando te toca estar despierto a esta misma hora un martes en la madrugada. 😯',
    'No tengo sueño y me deprimí y esto hago https://t.co/dDn1RxxWfd',
    '¿Cuanto es 1 + 1?',
    'Joder. Cuando trabaje debería tener horario nocturno.',
    "It's not just all physical 💟 https://t.co/lXE4WeLicQ",
    'Quiero el pene de Nout.',
    '@LaAhuyamita 😯😳',
    'Tenho q lembrar de tudo q preciso leva, principalmente o pacote de pirulito',
    "Pa' lante es pa alla.. y pa' atras ni pa mirar a los mios!",
    'Jajajajajsjjsakajsjs💜',
    'Escribir.',
    '@JervisDomenica no invitas x2 AJAJAJAAJJA',
    'Estranho seria se eu não me apaixonasse por você',
    'No tiene nada de malo irse cuando sientes que no estas avanzando.',
    '@thaysalejandraa bendecido desde el 2009 😂',
    '#Basquetebol #Rio2016 #BaladaOlimpica https://t.co/myB92r8PFi',
    'Si me pagaran por las veces que me dicen que soy super amargada, aguafiestas  e insoportable https://t.co/x8NTBXEDjX',
    "Pa' lante es pa alla.. y pa' atras ni pa saludar a los mios!",
    'Oye porque puedo estar perfectamente despierta toda la noche y con sueño todo el día.',
    'I miss you',
    'extraño como las cosas fueron el año pasado :(',
    'Sebastián si ves esto en tú tl sigue a @sebasmysunshine 🙌🙏',
    '@isaacpdro99 @JosephNieveeees  JAJAJAJJAA josep tu lo ves y te dices ati mismo sera que las boto tambien jjjajajaja',
    '@Frankyardigan @Pablonauta_ https://t.co/5gUT2eRBkv',
    'Again',
    'Que falta haces.. Cuánto daría por volverte a ver😔😟',
    'carai\nsó hoje (terça):\nfutebol fem, os 3 jogos do vôlei de praia, vôlei fem de quadra, o boxe com medalha + 83293 outros',
    'extraño como era yo antes',
    'https://t.co/4fOO1WrtuL',
    'Es que uno lee conversaciones y nos destruimos emocionalmente.',
    'Estranho é gostar tanto do seu all star azul, estranho é pensar que o bairro das Laranjeiras... Satisfeito sorri quando chego ali',
    'Mi dia a dia no es color de Rosa!',
    'Que hambre tan Hpta',
    'Juguemos v o r',
    'pero no me quejo de el presente',
    'Perdi la tranquilidad por tanto pensar',
    '@FilthyPanes pasa pa mandate uno',
    'Esta es la hora en la que te pienso🆚🆚💕\n #SebastiánVillalobosVídeo #SebastiánVillalobosYoutuber #KCAColombia',
    'Y aún no ha llegado ese ser. https://t.co/zLnNPZH89W',
    'Luces, camara y accion!!',
    'Quiero una maquina de hacer dinero... https://t.co/eaPOmzCkb2',
    'Asi es la vida...',
    'cuando era flaca y feliz. https://t.co/BELOldxFyR',
    '@dalboscoj @sandi_says por demais vivãos',
    'Maldita sea cuando pega hambre a esta hra',
    '@DonG0norrea Hoy en día es más difícil que quitarle la sonrisa a Caterine Ibargüen 💔.'
]
